In [1]:
#Importar las librerias
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
# Data_set MNIST http://yann.lecun.com/exdb/mnist/ 

In [2]:
mnist =  input_data.read_data_sets("../data", one_hot=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ../data\train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ../data\train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting ../data\t10k-images-idx3-ubyte.gz
Extracting ../data\t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [3]:
x = tf.placeholder(shape=[None, 784], dtype=tf.float32) #Entradas de la red
w = tf.Variable(tf.zeros([784, 10]) ) #Matiz de pesos de 784 "entradas" y 10 posibles salidas
#y = wx + b
b = tf.Variable(tf.zeros([10])) # Un tensor con los biases
y = tf.matmul(x,w)+b  #y = W x X + B
labels = tf.placeholder(tf.float32, [None, 10]) #Etiquetas para la clasificación

Instructions for updating:
Colocations handled automatically by placer.


## Definir la función de activación, luego costo y finalmente aplicar softmax 

In [4]:
logits = tf.sigmoid(y)
probs = tf.nn.softmax_cross_entropy_with_logits(labels=labels, logits=logits)
loss = tf.reduce_mean(probs)
#Learning rate
learning_rate = 0.1
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(loss)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



## Metricas de evaluación de la Red

In [25]:
correct_preds = tf.equal(tf.argmax(probs,axis=1), tf.argmax(labels, axis=1))
precission = tf.reduce_mean(tf.cast(correct_preds, tf.float32))
Production = tf.argmax(y,1) #aaa
init = tf.global_variables_initializer()

In [28]:
#Vamos a entrenar a la Red Neuronal
def train (epoc_i, session, last_feature, last_labels):
    loss_current = session.run (loss, feed_dict={x: last_feature, labels: last_labels})
    print(mnist.validation.labels)
    print(mnist.validation.images)
    accuracy = session.run(precission, feed_dict = {x:mnist.validation.images, labels: mnist.validation.labels })
    print('Epoca:{:<4} - Loss: {:<8.3} - Accuracy: {:<5.3}'.format(epoc_i, loss_current,accuracy))

In [29]:
with tf.Session() as session:
    session.run(init)
    for epoc_i in range (1000):
        batch_x, batch_y  = mnist.train.next_batch(100)
        session.run(optimizer, feed_dict ={x: batch_x, labels: batch_y})
        if (epoc_i%50==0):
            train (epoc_i, session, batch_x, batch_y)
    print ('Final result:', session.run(precission, feed_dict = {x: mnist.test.images, labels: mnist.test.labels}))
    print ('Image result',session.run(Production, fedd_dict= {x: mnist.test.images[5].reshape(1,784)}))

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


InvalidArgumentError: Expected dimension in the range [-1, 1), but got 1
	 [[node ArgMax_5 (defined at <ipython-input-25-c6e7a209a359>:1) ]]

Caused by op 'ArgMax_5', defined at:
  File "c:\programdata\anaconda3\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\development\deeplearning\deep_env\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "e:\development\deeplearning\deep_env\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "e:\development\deeplearning\deep_env\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "e:\development\deeplearning\deep_env\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "c:\programdata\anaconda3\Lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "c:\programdata\anaconda3\Lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "c:\programdata\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "e:\development\deeplearning\deep_env\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "e:\development\deeplearning\deep_env\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "e:\development\deeplearning\deep_env\lib\site-packages\tornado\gen.py", line 781, in inner
    self.run()
  File "e:\development\deeplearning\deep_env\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "e:\development\deeplearning\deep_env\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "e:\development\deeplearning\deep_env\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "e:\development\deeplearning\deep_env\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "e:\development\deeplearning\deep_env\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "e:\development\deeplearning\deep_env\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "e:\development\deeplearning\deep_env\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "e:\development\deeplearning\deep_env\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "e:\development\deeplearning\deep_env\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "e:\development\deeplearning\deep_env\lib\site-packages\IPython\core\interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "e:\development\deeplearning\deep_env\lib\site-packages\IPython\core\interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "e:\development\deeplearning\deep_env\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "e:\development\deeplearning\deep_env\lib\site-packages\IPython\core\interactiveshell.py", line 3049, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "e:\development\deeplearning\deep_env\lib\site-packages\IPython\core\interactiveshell.py", line 3214, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "e:\development\deeplearning\deep_env\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-c6e7a209a359>", line 1, in <module>
    correct_preds = tf.equal(tf.argmax(probs,axis=1), tf.argmax(labels, axis=1))
  File "e:\development\deeplearning\deep_env\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "e:\development\deeplearning\deep_env\lib\site-packages\tensorflow\python\ops\math_ops.py", line 86, in argmax
    return argmax_v2(input, axis, output_type, name)
  File "e:\development\deeplearning\deep_env\lib\site-packages\tensorflow\python\ops\math_ops.py", line 115, in argmax_v2
    return gen_math_ops.arg_max(input, axis, name=name, output_type=output_type)
  File "e:\development\deeplearning\deep_env\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 915, in arg_max
    name=name)
  File "e:\development\deeplearning\deep_env\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "e:\development\deeplearning\deep_env\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "e:\development\deeplearning\deep_env\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "e:\development\deeplearning\deep_env\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Expected dimension in the range [-1, 1), but got 1
	 [[node ArgMax_5 (defined at <ipython-input-25-c6e7a209a359>:1) ]]
